name: Create Image

on:
  workflow_call:
    inputs:
      PUSH:
        description: Whether or not to push the image to GHCR
        type: boolean
        default: true
    outputs:
      imageid:
        description: 'Image ID'
        value: ${{ jobs.create-image.outputs.imageid }}
      digest:
        description: 'Image digest'
        value: ${{ jobs.create-image.outputs.digest }}
      metadata:
        description: 'Build result metadata'
        value: ${{ jobs.create-image.outputs.metadata }}

jobs:
  create-image:
    outputs:
      imageid: ${{ steps.build-and-push.outputs.imageid }}
      digest: ${{ steps.build-and-push.outputs.imageid }}
      metadata: ${{ steps.build-and-push.outputs.imageid }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/sonarqube-scan-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        id: build-and-push
        with:
          platforms: linux/amd64,linux/arm64
          push: ${{ inputs.PUSH }}
          context: .
          labels: ${{ steps.meta.outputs.labels }}
          tags: ${{ steps.meta.outputs.tags }}
      - name: Attest the image build
        uses: actions/attest-build-provenance@v1
        if: inputs.PUSH
        id: attest
        with:
          subject-name: ghcr.io/${{ github.repository_owner }}/sonarqube-scan-action
          subject-digest: ${{ steps.build-and-push.outputs.digest }}
          push-to-registry: true
